// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.albul.model;

import com.albul.model.LeadAccount;
import com.albul.model.LeadAccountDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect LeadAccountDataOnDemand_Roo_DataOnDemand {
    
    declare @type: LeadAccountDataOnDemand: @Component;
    
    private Random LeadAccountDataOnDemand.rnd = new SecureRandom();
    
    private List<LeadAccount> LeadAccountDataOnDemand.data;
    
    public LeadAccount LeadAccountDataOnDemand.getNewTransientLeadAccount(int index) {
        LeadAccount obj = new LeadAccount();
        return obj;
    }
    
    public LeadAccount LeadAccountDataOnDemand.getSpecificLeadAccount(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        LeadAccount obj = data.get(index);
        Long id = obj.getId();
        return LeadAccount.findLeadAccount(id);
    }
    
    public LeadAccount LeadAccountDataOnDemand.getRandomLeadAccount() {
        init();
        LeadAccount obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return LeadAccount.findLeadAccount(id);
    }
    
    public boolean LeadAccountDataOnDemand.modifyLeadAccount(LeadAccount obj) {
        return false;
    }
    
    public void LeadAccountDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = LeadAccount.findLeadAccountEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'LeadAccount' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<LeadAccount>();
        for (int i = 0; i < 10; i++) {
            LeadAccount obj = getNewTransientLeadAccount(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
