// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.albul.model;

import com.albul.model.LeadAccount;
import com.albul.model.LeadAccountDataOnDemand;
import com.albul.model.LeadAccountIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect LeadAccountIntegrationTest_Roo_IntegrationTest {
    
    declare @type: LeadAccountIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: LeadAccountIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: LeadAccountIntegrationTest: @Transactional;
    
    @Autowired
    LeadAccountDataOnDemand LeadAccountIntegrationTest.dod;
    
    @Test
    public void LeadAccountIntegrationTest.testCountLeadAccounts() {
        Assert.assertNotNull("Data on demand for 'LeadAccount' failed to initialize correctly", dod.getRandomLeadAccount());
        long count = LeadAccount.countLeadAccounts();
        Assert.assertTrue("Counter for 'LeadAccount' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void LeadAccountIntegrationTest.testFindLeadAccount() {
        LeadAccount obj = dod.getRandomLeadAccount();
        Assert.assertNotNull("Data on demand for 'LeadAccount' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'LeadAccount' failed to provide an identifier", id);
        obj = LeadAccount.findLeadAccount(id);
        Assert.assertNotNull("Find method for 'LeadAccount' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'LeadAccount' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void LeadAccountIntegrationTest.testFindAllLeadAccounts() {
        Assert.assertNotNull("Data on demand for 'LeadAccount' failed to initialize correctly", dod.getRandomLeadAccount());
        long count = LeadAccount.countLeadAccounts();
        Assert.assertTrue("Too expensive to perform a find all test for 'LeadAccount', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<LeadAccount> result = LeadAccount.findAllLeadAccounts();
        Assert.assertNotNull("Find all method for 'LeadAccount' illegally returned null", result);
        Assert.assertTrue("Find all method for 'LeadAccount' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void LeadAccountIntegrationTest.testFindLeadAccountEntries() {
        Assert.assertNotNull("Data on demand for 'LeadAccount' failed to initialize correctly", dod.getRandomLeadAccount());
        long count = LeadAccount.countLeadAccounts();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<LeadAccount> result = LeadAccount.findLeadAccountEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'LeadAccount' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'LeadAccount' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void LeadAccountIntegrationTest.testFlush() {
        LeadAccount obj = dod.getRandomLeadAccount();
        Assert.assertNotNull("Data on demand for 'LeadAccount' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'LeadAccount' failed to provide an identifier", id);
        obj = LeadAccount.findLeadAccount(id);
        Assert.assertNotNull("Find method for 'LeadAccount' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyLeadAccount(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'LeadAccount' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void LeadAccountIntegrationTest.testMergeUpdate() {
        LeadAccount obj = dod.getRandomLeadAccount();
        Assert.assertNotNull("Data on demand for 'LeadAccount' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'LeadAccount' failed to provide an identifier", id);
        obj = LeadAccount.findLeadAccount(id);
        boolean modified =  dod.modifyLeadAccount(obj);
        Integer currentVersion = obj.getVersion();
        LeadAccount merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'LeadAccount' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void LeadAccountIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'LeadAccount' failed to initialize correctly", dod.getRandomLeadAccount());
        LeadAccount obj = dod.getNewTransientLeadAccount(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'LeadAccount' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'LeadAccount' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'LeadAccount' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void LeadAccountIntegrationTest.testRemove() {
        LeadAccount obj = dod.getRandomLeadAccount();
        Assert.assertNotNull("Data on demand for 'LeadAccount' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'LeadAccount' failed to provide an identifier", id);
        obj = LeadAccount.findLeadAccount(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'LeadAccount' with identifier '" + id + "'", LeadAccount.findLeadAccount(id));
    }
    
}
